//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/6/2020 9:33:50 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace EFarmerPkModelLibrary.Entities
{
    public partial class SELLERSFAVORITESBUYER {

        public SELLERSFAVORITESBUYER()
        {
            OnCreated();
        }

        public virtual USER USER_SellerId
        {
            get;
            set;
        }

        public virtual USER USER_BuyerId
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          SELLERSFAVORITESBUYER toCompare = obj as SELLERSFAVORITESBUYER;
          if (toCompare == null)
          {
            return false;
          }


          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          return hashCode;
        }

        #endregion
    }

}
