//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/6/2020 9:30:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace EFarmerPkModelLibrary.Entities
{
    public partial class USER {

        public USER()
        {
            this.ADVERTISEMENTs_SellerId = new List<ADVERTISEMENT>();
            this.BUYERADDSDIFFERENTADSTOFAVs_BuyerId = new List<BUYERADDSDIFFERENTADSTOFAV>();
            this.BUYERSADDAGROITEMTOINTERESTs_BuyerId = new List<BUYERSADDAGROITEMTOINTEREST>();
            this.SELLERSFAVORITESBUYERs_SellerId = new List<SELLERSFAVORITESBUYER>();
            this.SELLERSFAVORITESBUYERs_BuyerId = new List<SELLERSFAVORITESBUYER>();
            OnCreated();
        }

        public virtual long Id
        {
            get;
            set;
        }

        public virtual string FName
        {
            get;
            set;
        }

        public virtual string LName
        {
            get;
            set;
        }

        public virtual string CCompanyCode
        {
            get;
            set;
        }

        public virtual string CCountryCode
        {
            get;
            set;
        }

        public virtual string CPhone
        {
            get;
            set;
        }

        public virtual string Address
        {
            get;
            set;
        }

        public virtual decimal? GLat
        {
            get;
            set;
        }

        public virtual decimal? GLng
        {
            get;
            set;
        }

        public virtual bool BuyerFlag
        {
            get;
            set;
        }

        public virtual bool SellerFlag
        {
            get;
            set;
        }

        public virtual IList<ADVERTISEMENT> ADVERTISEMENTs_SellerId
        {
            get;
            set;
        }

        public virtual IList<BUYERADDSDIFFERENTADSTOFAV> BUYERADDSDIFFERENTADSTOFAVs_BuyerId
        {
            get;
            set;
        }

        public virtual IList<BUYERSADDAGROITEMTOINTEREST> BUYERSADDAGROITEMTOINTERESTs_BuyerId
        {
            get;
            set;
        }

        public virtual IList<SELLERSFAVORITESBUYER> SELLERSFAVORITESBUYERs_SellerId
        {
            get;
            set;
        }

        public virtual IList<SELLERSFAVORITESBUYER> SELLERSFAVORITESBUYERs_BuyerId
        {
            get;
            set;
        }

        public virtual CITY City
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
