//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/6/2020 9:30:53 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace EFarmerPkModelLibrary.Entities
{
    public partial class BUYERADDSDIFFERENTADSTOFAV {

        private ILazyLoader lazyLoader;
        protected BUYERADDSDIFFERENTADSTOFAV(ILazyLoader lazyLoader)
        {
            this.lazyLoader = lazyLoader;
        }
        public BUYERADDSDIFFERENTADSTOFAV()
        {
            OnCreated();
        }

        public virtual ADVERTISEMENT ADVERTISEMENT
        {
            get;
            set;
        }

        public virtual USER Buyer
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          BUYERADDSDIFFERENTADSTOFAV toCompare = obj as BUYERADDSDIFFERENTADSTOFAV;
          if (toCompare == null)
          {
            return false;
          }


          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          return hashCode;
        }

        #endregion
    }

}
